name: Docker Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: v35-php74
        run: docker build wikibase-35/
